### PR TITLE
Product Database Setup, CRUD API for Product

### PR DESCRIPTION
**Pull request by alexmeigz**

### CODE REVIEW

**Comment by alexmeigz** [comment]
[Setup Product Database](https://trello.com/c/maA04Gb6/23-setup-product-database)

**Comment by alexmeigz** [comment]
[Product Controller: Create](https://trello.com/c/x2oW81Y7/26-product-controller-create)

**Comment by alexmeigz** [comment]
[Create Product Model](https://trello.com/c/Q8K4YWXQ/28-create-product-model)

**Comment by alexmeigz** [comment]
[Product Controller: Read](https://trello.com/c/MXWXX6wJ/73-product-controller-read)

**Comment by alexmeigz** [comment]
[Setup Project Files](https://trello.com/c/BTBzuSoY/37-setup-project-files)

**Comment by alexmeigz** [comment]
[Product Controller: Update](https://trello.com/c/1WppbHH8/71-product-controller-update)

**Comment by alexmeigz** [comment]
[Product Controller: Delete](https://trello.com/c/CMGjJQgj/72-product-controller-delete)

**Review by pranav01acharya — APPROVED** [review]

**Pull request merged**
