### PR TITLE
Post API CRUD, Fix Merge Conflicts

### PR DESCRIPTION
**Pull request by alexmeigz**

### CODE REVIEW

**Review by sriya112 — APPROVED** [review]

**Comment by alexmeigz** [comment]
[Post Database](https://trello.com/c/EmAw4ZvH/129-post-database)

**Comment by alexmeigz** [comment]
[Post Model](https://trello.com/c/Y76YwJuE/128-post-model)

**Comment by alexmeigz** [comment]
[Post Controller: Create](https://trello.com/c/5GINNsnp/133-post-controller-create)

**Comment by alexmeigz** [comment]
[Post Controller: Read](https://trello.com/c/2T9tGDgb/130-post-controller-read)

**Comment by alexmeigz** [comment]
[Post Controller: Delete](https://trello.com/c/KiqHup1g/135-post-controller-delete)

**Comment by alexmeigz** [comment]
[Post Controller: Update](https://trello.com/c/6ZYJFjjc/134-post-controller-update)

**Comment by alexmeigz** [comment]
[Post Controller: Display All](https://trello.com/c/RBDyaNDN/192-post-controller-display-all)

**Comment by alexmeigz** [comment]
[Post Controller: Display All](https://trello.com/c/RBDyaNDN/192-post-controller-display-all)

**Pull request merged**
